rpc:
  name: eRpc-framework
  version: 2.0.0
  mock: false
  serializer: kryo
  serverHost: localhost
  serverPort: 9998
  registryConfig:
    host: localhost
    timeout: 1000L
    port: 2181
    registry: zookeeper
  retryStrategy: fixedInterval
server:
  port: 8082

